server {
    listen 80;
    listen [::]:80;
    server_name ly.echoxai.net;

    access_log off;
    location ^~ /.well-known/acme-challenge/ {
        root /var/www/lingyuan-acme;
    }

    location / {
        return 503;
    }
}
